language: node_js
node_js:
- 10
before_install:
- chmod +x ./prod-install.sh
- chmod +x ./prod-build.sh
install: "./prod-install.sh"
script: "./prod-build.sh"
deploy:
  provider: heroku
  api_key:
    secure: PK3/SRGwQPJ1C3/CikKvONGMf+GXnGMY9yyWINlJLDdC085dYjaOgIbE8ce7Nza5XJ0RW+IxiKlSlzqyb1rQA5j7F6ARTG7/NAT1nMKc61TFYWpEheV2893Sv93yuHalyHafFoQjr2WIWpkBvNnSkRYdsn+JbhMw/aSlY4PpuYPiVSzriE8WtgKaXwwDTKSKZD8b5CDHiFySTgJucPgKdHnnMYy5vJh7VeDVBogtGzDxRQTFs4hfUOFrLG42V8sfzIZm1iZs64PihZ42dyZFPRwJDZQg4ZXqHW1X89xOQBXqB1kY9aKRZXc8qzttcVizHBLGidIklQa4/RCxlTnwGfeV/XPLewNfMsRmgWjuUpnhtKpCv7tv1BTGa3TxNXxrQqIEmUYPg+akSsHcc4aC3g1oaIzCOp3Opgbew0NGyfZ+PMf4W4NUS+UBpmV2W9/0EaSXYEfxyCV2dTfwdpo8Io2sm/1sX5AoB11AC3AWPIukbX6sDp+FXT9dKmrlq9DkVCanAWH01p/tjNB8z2BFj6Y84ZFnpVSqTMwzupEGLGqNxkuc42VNSZrnD+WCdczItMZSf2M2wQP+1juG8Ga2YeoqRoS9+pmv0fO7sRUwd8hZJt9RV6DF95+Eh1F/BGn1EBPyutcGQFFaMSbhgLiDukLtJd3XReLGr5yIyjjCqnk=
  app: yamtgdb
